name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ aaden.online }}
        user: ${{ u172534159.chao }}
        password: ${{ Innerken322. }}
        localDir: "dist"
        remoteDir: "changeLog"
        options: "--delete --asci"
